name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: pytest - OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - pandas ${{ matrix.pandas-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        pandas-version: ["1.3", "1.4", ""]
        exclude:
          - python-version: "3.6"
            pandas-version: "1.3"
          - python-version: "3.6"
            pandas-version: "1.4"
          - python-version: "3.7"
            pandas-version: "1.3"
          - python-version: "3.7"
            pandas-version: "1.4"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install -e .
    - name: Replace with specific pandas version (${{ matrix.pandas-version }})
      if: ${{ matrix.pandas-version }}
      run: pip install pandas==${{ matrix.pandas-version }}
    - name: Test with pytest
      run: |
        pytest --cov=pandarallel
